// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: kademlia_grpc.proto

package knp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Header) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

type PingArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Address string  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *PingArgs) Reset() {
	*x = PingArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingArgs) ProtoMessage() {}

func (x *PingArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingArgs.ProtoReflect.Descriptor instead.
func (*PingArgs) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *PingArgs) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PingArgs) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Address  string     `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Contacts []*Contact `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *PingReply) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PingReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PingReply) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type StoreArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Key     string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Handler string  `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`
	Value   []byte  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StoreArgs) Reset() {
	*x = StoreArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreArgs) ProtoMessage() {}

func (x *StoreArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreArgs.ProtoReflect.Descriptor instead.
func (*StoreArgs) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *StoreArgs) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StoreArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreArgs) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *StoreArgs) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StoreReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value  []byte  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StoreReply) Reset() {
	*x = StoreReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreReply) ProtoMessage() {}

func (x *StoreReply) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreReply.ProtoReflect.Descriptor instead.
func (*StoreReply) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *StoreReply) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StoreReply) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type FindValueArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header  *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Key     string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Handler string  `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`
	Value   []byte  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FindValueArgs) Reset() {
	*x = FindValueArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindValueArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValueArgs) ProtoMessage() {}

func (x *FindValueArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValueArgs.ProtoReflect.Descriptor instead.
func (*FindValueArgs) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{5}
}

func (x *FindValueArgs) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FindValueArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FindValueArgs) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *FindValueArgs) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type FindValueReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value  []byte  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *FindValueReply) Reset() {
	*x = FindValueReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindValueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValueReply) ProtoMessage() {}

func (x *FindValueReply) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValueReply.ProtoReflect.Descriptor instead.
func (*FindValueReply) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{6}
}

func (x *FindValueReply) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FindValueReply) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type FindNodeArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Header `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id     string  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindNodeArgs) Reset() {
	*x = FindNodeArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNodeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeArgs) ProtoMessage() {}

func (x *FindNodeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeArgs.ProtoReflect.Descriptor instead.
func (*FindNodeArgs) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{7}
}

func (x *FindNodeArgs) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FindNodeArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindNodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Header    `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Contacts []*Contact `protobuf:"bytes,2,rep,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *FindNodeReply) Reset() {
	*x = FindNodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNodeReply) ProtoMessage() {}

func (x *FindNodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNodeReply.ProtoReflect.Descriptor instead.
func (*FindNodeReply) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{8}
}

func (x *FindNodeReply) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FindNodeReply) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kademlia_grpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_grpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_kademlia_grpc_proto_rawDescGZIP(), []int{9}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_kademlia_grpc_proto protoreflect.FileDescriptor

var file_kademlia_grpc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6b, 0x6e, 0x70, 0x22, 0x3c, 0x0a, 0x06, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x74, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x23, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x28, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x22, 0x72, 0x0a, 0x09, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x47, 0x0a,
	0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x6e,
	0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x76, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4b,
	0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x23, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x43, 0x0a, 0x0c, 0x46,
	0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x72, 0x67, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x6e,
	0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x5e, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x23, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73,
	0x22, 0x33, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0xcb, 0x01, 0x0a, 0x0f, 0x4b, 0x61, 0x64, 0x65, 0x6d, 0x6c,
	0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x0d, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x0e, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x28, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x0e, 0x2e, 0x6b, 0x6e, 0x70, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0f, 0x2e, 0x6b, 0x6e, 0x70, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x09, 0x46, 0x69,
	0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x13, 0x2e, 0x6b, 0x6e,
	0x70, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x31, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x11, 0x2e, 0x6b,
	0x6e, 0x70, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x12, 0x2e, 0x6b, 0x6e, 0x70, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x3b, 0x6b, 0x6e, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kademlia_grpc_proto_rawDescOnce sync.Once
	file_kademlia_grpc_proto_rawDescData = file_kademlia_grpc_proto_rawDesc
)

func file_kademlia_grpc_proto_rawDescGZIP() []byte {
	file_kademlia_grpc_proto_rawDescOnce.Do(func() {
		file_kademlia_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_kademlia_grpc_proto_rawDescData)
	})
	return file_kademlia_grpc_proto_rawDescData
}

var file_kademlia_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_kademlia_grpc_proto_goTypes = []any{
	(*Header)(nil),         // 0: knp.Header
	(*PingArgs)(nil),       // 1: knp.PingArgs
	(*PingReply)(nil),      // 2: knp.PingReply
	(*StoreArgs)(nil),      // 3: knp.StoreArgs
	(*StoreReply)(nil),     // 4: knp.StoreReply
	(*FindValueArgs)(nil),  // 5: knp.FindValueArgs
	(*FindValueReply)(nil), // 6: knp.FindValueReply
	(*FindNodeArgs)(nil),   // 7: knp.FindNodeArgs
	(*FindNodeReply)(nil),  // 8: knp.FindNodeReply
	(*Contact)(nil),        // 9: knp.Contact
}
var file_kademlia_grpc_proto_depIdxs = []int32{
	0,  // 0: knp.PingArgs.header:type_name -> knp.Header
	0,  // 1: knp.PingReply.header:type_name -> knp.Header
	9,  // 2: knp.PingReply.contacts:type_name -> knp.Contact
	0,  // 3: knp.StoreArgs.header:type_name -> knp.Header
	0,  // 4: knp.StoreReply.header:type_name -> knp.Header
	0,  // 5: knp.FindValueArgs.header:type_name -> knp.Header
	0,  // 6: knp.FindValueReply.header:type_name -> knp.Header
	0,  // 7: knp.FindNodeArgs.header:type_name -> knp.Header
	0,  // 8: knp.FindNodeReply.header:type_name -> knp.Header
	9,  // 9: knp.FindNodeReply.contacts:type_name -> knp.Contact
	1,  // 10: knp.KademliaService.Ping:input_type -> knp.PingArgs
	3,  // 11: knp.KademliaService.Store:input_type -> knp.StoreArgs
	5,  // 12: knp.KademliaService.FindValue:input_type -> knp.FindValueArgs
	7,  // 13: knp.KademliaService.FindNode:input_type -> knp.FindNodeArgs
	2,  // 14: knp.KademliaService.Ping:output_type -> knp.PingReply
	4,  // 15: knp.KademliaService.Store:output_type -> knp.StoreReply
	6,  // 16: knp.KademliaService.FindValue:output_type -> knp.FindValueReply
	8,  // 17: knp.KademliaService.FindNode:output_type -> knp.FindNodeReply
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_kademlia_grpc_proto_init() }
func file_kademlia_grpc_proto_init() {
	if File_kademlia_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kademlia_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PingArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StoreArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*StoreReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FindValueArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*FindValueReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*FindNodeArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*FindNodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kademlia_grpc_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kademlia_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kademlia_grpc_proto_goTypes,
		DependencyIndexes: file_kademlia_grpc_proto_depIdxs,
		MessageInfos:      file_kademlia_grpc_proto_msgTypes,
	}.Build()
	File_kademlia_grpc_proto = out.File
	file_kademlia_grpc_proto_rawDesc = nil
	file_kademlia_grpc_proto_goTypes = nil
	file_kademlia_grpc_proto_depIdxs = nil
}
